import os

APP_SECRET_KEY = os.environ['APP_SECRET_KEY']
DATABASE_URL = os.environ['DATABASE_URL']
TWITTER_API_KEY = os.environ['TWITTER_API_KEY']
TWITTER_API_SECRET = os.environ['TWITTER_API_SECRET']
